version: 2
updates:
- package-ecosystem: npm
  directory: /functions
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - ssilver
  labels:
  - dependencies
  commit-message:
    prefix: deps
